version: '3.9'
services: 

  reverse-proxy:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    container_name: reverse-proxy
    ports:
      - 80:8080
      - 443:8443
    restart: on-failure

  relational-database:
    image: postgres:latest
    container_name: relational-database
    ports: 
      - 5432:5432
    env_file:
      - ./postgresql.env
      - ./postgresql-credentials.env
    volumes:
      - ./relational-database/:/docker-entrypoint-initdb.d/
    restart: on-failure

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    restart: on-failure

  web-server:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - 3000:3000
    restart: on-failure

  app-server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: app-server
    env_file:
      - ./postgresql.env
      - ./postgresql-credentials.env
      - ./secrets.env
    ports:
      - 4000:4000
    volumes:
      - ./objects/:/app/objects
    restart: on-failure

